



services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html

  php-cli:
    image: php:7.4-cli
    container_name: php-cli
    volumes:
      - ./html:/var/www/html
    working_dir: /var/www/html
