# Используем базовый образ PHP с FPM 8.2
FROM php:8.2-fpm

# Установка необходимых PHP расширений
RUN docker-php-ext-install pdo pdo_mysql

# Копирование пользовательских настроек PHP
COPY .php.ini /usr/local/etc/php/conf.d/php-custom.ini

# Установка Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Установка zip
RUN apt-get update && apt-get install -y zip

WORKDIR /var/www/html

# Установим необходимый пакет TWIG
RUN composer require "twig/twig:^3.0"

# Создаем volume для постоянного хранения данных
VOLUME /var/www/html
